version: "1"

services:
  zookeeper-1:
    container_name: zookeeper-1
    image: 'bitnami/zookeeper:latest'
    networks: 
      - docker_kafka_net
    ports:
      - '22181:2181'
    environment:
      - ZOO_PORT_NUMBER=2181
      - ZOO_TICK_TIME=2000
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - "$PWD/logs/zookeeper-1:/bitnami/zookeeper"

  zookeeper-2:
    container_name: zookeeper-2
    image: 'bitnami/zookeeper:latest'
    networks: 
      - docker_kafka_net
    ports:
      - '32181:2181'
    environment:
      - ZOO_PORT_NUMBER=2181
      - ZOO_TICK_TIME=2000
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - "$PWD/logs/zookeeper-2:/bitnami/zookeeper"

  kafka-1:
    container_name: kafka-1
    image: 'bitnami/kafka:latest'
    networks: 
      - docker_kafka_net
    ports:
      - '29092:29092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1:2181,zookeeper-2:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka-1:9092,EXTERNAL://localhost:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    volumes:
      - "$PWD/logs/kafka-1:/bitnami/kafka"
    depends_on:
      - zookeeper-1
      - zookeeper-2

  kafka-2:
    container_name: kafka-2
    image: 'bitnami/kafka:latest'
    networks: 
      - docker_kafka_net
    ports:
      - '39092:39092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1:2181,zookeeper-2:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:39092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka-2:9092,EXTERNAL://localhost:39092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    volumes:
      - "$PWD/logs/kafka-2:/bitnami/kafka"
    depends_on:
      - zookeeper-1
      - zookeeper-2

networks:
  docker_kafka_net:
    name: "docker_kafka_net"
    driver: bridge